import discord
from discord.ext import commands
from core.classes import Cog_Extension

class Basic(Cog_Extension):
    #ping(ms)
    @commands.command()
    async def ping(self, ctx):
        await ctx.send(f'{round(self.bot.latency*1000)} ms')
    
    @commands.command()
    async def about(self, ctx):
        # Generated by https://cog-creators.github.io/discord-embed-sandbox/
        embed=discord.Embed(title="智能垃圾桶", url="https://github.com/mariokart761/FCU-Embedding-Final", description="1112-FCU-嵌入式系統設計與實務-期末專案", color=0xf00000)
        embed.set_author(name="ZHU-JIA-LE", url="https://github.com/mariokart761", icon_url="https://cdn.discordapp.com/avatars/324809296602726400/0dbdce723d977eaadcc9cfda55666d38.webp")
        embed.set_thumbnail(url="https://cdn.discordapp.com/attachments/862518605433012268/1104852774493114549/trash-can.png")
        embed.add_field(name="成員", value="ZHU-JIA-LE", inline=True)
        embed.set_footer(text="Discord : AyanoMyWaifu#0980")
        await ctx.send(embed=embed)
        
async def setup(bot):
    await bot.add_cog(Basic(bot))